### pandas - where

In [1]:
import pandas as pd
import numpy as np

In [ ]:
np.where(condition)

In [3]:
array = np.random.randint(10,30,size = 10)
array

array([21, 29, 16, 23, 18, 17, 13, 15, 13, 19])

In [6]:
index = np.where(array >= 20)[0]
index

array([0, 1, 3], dtype=int64)

In [7]:
array[index]

array([21, 29, 23])

In [23]:
array = np.random.randint(10,30,size = 10)
numbers = array[np.where(array >= 20)[0]]
numbers

array([27, 23, 29, 24, 25])

In [25]:
numbers = np.where(array >= 20,200,100)
numbers

array([100, 200, 100, 200, 200, 100, 100, 200, 200, 100])

In [27]:
numbers = np.where(array >= 20,1,0)
numbers

array([0, 1, 0, 1, 1, 0, 0, 1, 1, 0])

In [29]:
numbers = np.where(array >= 20,'T','F')
numbers

array(['F', 'T', 'F', 'T', 'T', 'F', 'F', 'T', 'T', 'F'], dtype='<U1')

In [31]:
numbers = np.where(array >= 20,200,array)
numbers

array([ 15, 200,  17, 200, 200,  10,  10, 200, 200,  13])

In [32]:
numbers = np.where(array >= 20,array,0)
numbers

array([ 0, 27,  0, 23, 29,  0,  0, 24, 25,  0])

In [36]:
emp_df = pd.read_csv('Emp_data.csv').head(10)
emp_df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0  677509       Lois       36.36             60           13.68  168251   
1  940761     Brenda       47.02             60            9.01   51063   
2  428945        Joe       54.15             68            0.98   50155   
3  408351      Diane       39.67             51           18.30  180294   
4  193819   Benjamin       40.31             58            4.01  117642   
5  499687    Patrick       34.86             58           12.02   72305   
6  539712      Nancy       22.14             50            0.87   98189   
7  380086      Carol       59.12             40           34.52   60918   
8  477616    Frances       58.18             42           23.27  121587   
9  162402      Diana       29.73             60            3.44   43010   

             City  
0          Denver  
1       Stonewall  
2    Michigantown  
3        Hydetown  
4         Fremont  
5       Macksburg  
6         Atlanta  
7     Blanchester  
8         Delmita  
9  Eureka Springs

In [37]:
np.where(emp_df['Salary'] >= 100000,'High', 'Low')

array(['High', 'Low', 'Low', 'High', 'High', 'Low', 'Low', 'Low', 'High',
       'Low'], dtype='<U4')

In [39]:
emp_df['Salary'] = np.where(emp_df['Salary'] >= 100000,'High', 'Low')
emp_df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company Salary  \
0  677509       Lois       36.36             60           13.68   High   
1  940761     Brenda       47.02             60            9.01    Low   
2  428945        Joe       54.15             68            0.98    Low   
3  408351      Diane       39.67             51           18.30   High   
4  193819   Benjamin       40.31             58            4.01   High   
5  499687    Patrick       34.86             58           12.02    Low   
6  539712      Nancy       22.14             50            0.87    Low   
7  380086      Carol       59.12             40           34.52    Low   
8  477616    Frances       58.18             42           23.27   High   
9  162402      Diana       29.73             60            3.44    Low   

             City  
0          Denver  
1       Stonewall  
2    Michigantown  
3        Hydetown  
4         Fremont  
5       Macksburg  
6         Atlanta  
7     Blanchester  
8         Delmita  
9  Eureka Springs

In [49]:
emp_df = pd.read_csv('Emp_data.csv').head(10)
emp_df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0  677509       Lois       36.36             60           13.68  168251   
1  940761     Brenda       47.02             60            9.01   51063   
2  428945        Joe       54.15             68            0.98   50155   
3  408351      Diane       39.67             51           18.30  180294   
4  193819   Benjamin       40.31             58            4.01  117642   
5  499687    Patrick       34.86             58           12.02   72305   
6  539712      Nancy       22.14             50            0.87   98189   
7  380086      Carol       59.12             40           34.52   60918   
8  477616    Frances       58.18             42           23.27  121587   
9  162402      Diana       29.73             60            3.44   43010   

             City  
0          Denver  
1       Stonewall  
2    Michigantown  
3        Hydetown  
4         Fremont  
5       Macksburg  
6         Atlanta  
7     Blanchester  
8         Delmita  
9  Eureka Springs

In [52]:
emp_df = pd.read_csv('Emp_data.csv').head(10)
emp_df['Salary'] = np.where(emp_df['Salary'] >= 150000, 'High', 
                            np.where(emp_df['Salary'] >= 90000,'Medium','Low'))

emp_df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0  677509       Lois       36.36             60           13.68    High   
1  940761     Brenda       47.02             60            9.01     Low   
2  428945        Joe       54.15             68            0.98     Low   
3  408351      Diane       39.67             51           18.30    High   
4  193819   Benjamin       40.31             58            4.01  Medium   
5  499687    Patrick       34.86             58           12.02     Low   
6  539712      Nancy       22.14             50            0.87  Medium   
7  380086      Carol       59.12             40           34.52     Low   
8  477616    Frances       58.18             42           23.27  Medium   
9  162402      Diana       29.73             60            3.44     Low   

             City  
0          Denver  
1       Stonewall  
2    Michigantown  
3        Hydetown  
4         Fremont  
5       Macksburg  
6         Atlanta  
7     Blanchester  
8         Delmita  
9  Eureka Springs

### map

In [54]:
emp_df = pd.read_csv('Emp_data.csv').head(10)
emp_df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0  677509       Lois       36.36             60           13.68  168251   
1  940761     Brenda       47.02             60            9.01   51063   
2  428945        Joe       54.15             68            0.98   50155   
3  408351      Diane       39.67             51           18.30  180294   
4  193819   Benjamin       40.31             58            4.01  117642   
5  499687    Patrick       34.86             58           12.02   72305   
6  539712      Nancy       22.14             50            0.87   98189   
7  380086      Carol       59.12             40           34.52   60918   
8  477616    Frances       58.18             42           23.27  121587   
9  162402      Diana       29.73             60            3.44   43010   

             City  
0          Denver  
1       Stonewall  
2    Michigantown  
3        Hydetown  
4         Fremont  
5       Macksburg  
6         Atlanta  
7     Blanchester  
8         Delmita  
9  Eureka Springs

In [60]:
emp_df['City'].replace({'Denver':'Paris','Atlanta':"London"})

0             Paris
1         Stonewall
2      Michigantown
3          Hydetown
4           Fremont
5         Macksburg
6            London
7       Blanchester
8           Delmita
9    Eureka Springs
Name: City, dtype: object

In [61]:
emp_df['City'].map({'Denver':'Paris','Atlanta':"London"})

0     Paris
1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
6    London
7       NaN
8       NaN
9       NaN
Name: City, dtype: object