# Pandas

In [ ]:
Pandas is a Python Open Source Library built on top of Numpy

Pandas >> Python Data Analysis

Uses:
    1. Pandas has functions, to analyse the Big Data and develop conclusions based on 
       statistical theories
    2. Data - analysis, cleansing, modification is possible using Pandas
    3. It offers various Data Structures and Operations for manipulating Numerical Data and
       Time Series
    4. Pandas can clean messy data and make it readable and relevant.
    5. Relevant data is very important in Data Science.
    6. Pandas is faster and high-performance and Productive.
    
Use Cases:
    1. To read data from csv, excel, JSON, STAT files
    2. To read data from Data Structures (SQL, NoSQL)
    3. To write data to csv, excel, JSON,STAT files
    4. To write data to Data Structures (SQL, NoSQL)
    5. Cleansing of Data: Missing Values, Outliers handling
    6. Encoding:
            Label Encoding
            One Hot Encoding
    7. EDA - Exploratory Data Analysis
    8. Feature Selection
    9. Join multiple tables
    10. Provide Time Series Functionality
    11. Data Visualization: using following libraries
        seaborn
        matplotlib
        plotly

Statistical Analysis of Data in finding:
    min
    mean
    median
    mode
    standard deviation
    variance
    quantilies (25%, 50%, 75%)
    max
    
Data Frame/Series are >> size, values of Tabular Data are Mutable
                      >> Heterogeneous Datatypes

### Advantages of Pandas

In [ ]:
1. Fast and efficient for manipulating and analyzing data.
2. Data from different file objects can be loaded (csv, JSON, xlsx, DAT).
3. Easy handling of missing data (represented as NaN) in floating point as well as 
   non-floating point data
4. Size mutability: columns can be inserted and deleted from DataFrame 
    and higher dimensional objects
5. Data set merging and joining.
6. Flexible reshaping and pivoting of data sets
7. Provides time-series functionality.
8. Powerful "group by" functionality for performing split-apply-combine operations 
   on data sets.

### Importing of Pandas Library in Python

In [ ]:
import keyword is used for importing the pandas library. 
pandas will be imported as pd (aliasing the name)

Both Numpy and Pandas has to import to workon.

In [5]:
import pandas as pd

In [6]:
import numpy as np

#### Warnings Turn Off

In [ ]:
In Pandas, we usually get warnings from the source code. In such cases to avoid those warnings

import warnings
warnings.filterwarnings('ignore')

## Data Structures

In [ ]:
Two Types:
    1. Series     --> One Dimensional Data Structure - 1D       >> column data
    2. Data Frame --> Two Dimentional Data Structure - 2D       >> rows & columns as Table

#### 1. Series Data Structure

In [ ]:
Series: 
    - Pandas Series is One Dimensional labelled array holding the data of any data type. 
      (int, float, str, python object etc)
    - It is Column in Excel.

    Rows   - Indexes starts from 0 by default
    Column - Data

Syntax:
    s1 = pd.Series(data, index = None, dtype = None)
    
data: one dimentional array, list, tuple, dict (key --> row labels, value --> col values)
index: row labels (optional)
dtype: inferred from data (optional)

Default DataType of Series is: float         Futurewarning will occur
        Note: if mention dtype = object      Futurewarning will go off.
        
Datatype of Pandas Series Object:
    pandas.core.series.Series

#### Creating Pandas Series

In [55]:
# Using Numpy Array
array = np.random.randint(range(10,20))
print(array, type(array))
s1 = pd.Series(array)                
s1

[ 5  5 11  4 11 10 14 10  5  0] <class 'numpy.ndarray'>


0     5
1     5
2    11
3     4
4    11
5    10
6    14
7    10
8     5
9     0
dtype: int32

In [56]:
type(s1)               # DataType of Pandas Series Object

pandas.core.series.Series

In [10]:
# Using Lists

list1 = [1,2,3,4,5,6]
s2 = pd.Series(list1)
print(s2)
print(type(s2))

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>


In [11]:
# Using Tuple

tuple1 = ('P','Y','T','H','O','N')
s2 = pd.Series(tuple1)                
s2

0    P
1    Y
2    T
3    H
4    O
5    N
dtype: object

In [14]:
# Using Dictionary
"""In Dict:
    Keys   --> rows
    Values --> values of that row"""

dict1 = {'P':10,'Y':11,'T':12,'H':13,'O':14,'N':15}
s2 = pd.Series(dict1)                           
s2

P    10
Y    11
T    12
H    13
O    14
N    15
dtype: int64

In [15]:
# Creating Empty Series

s1 = pd.Series()
s1                        # As Default DataType is: float --> Future Warning will occur

C:\Users\Kiran\AppData\Local\Temp\ipykernel_10164\3141469608.py:3: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s1 = pd.Series()


Series([], dtype: float64)

In [53]:
s1 = pd.Series(dtype = object)            # if mentioned dtype = object, warning will go off
s1

Series([], dtype: object)

In [24]:
array = np.random.randint(range(10,20))
print(array, type(array))


[ 8  5  5  7  0  8  1  6  7 14] <class 'numpy.ndarray'>


In [29]:
pd.Series([1,2,3,4.5,10,3])              # if one item is float, then whole datatype is float

0     1.0
1     2.0
2     3.0
3     4.5
4    10.0
5     3.0
dtype: float64

In [30]:
pd.Series([1,2,3,4,10,3])

0     1
1     2
2     3
3     4
4    10
5     3
dtype: int64

In [25]:
s1 = pd.Series(array, dtype = int)      # Dtype can be modified as per user requirement
s1                              

0     8
1     5
2     5
3     7
4     0
5     8
6     1
7     6
8     7
9    14
dtype: int32

In [31]:
s1 = pd.Series(array, dtype = float)
s1

0     8.0
1     5.0
2     5.0
3     7.0
4     0.0
5     8.0
6     1.0
7     6.0
8     7.0
9    14.0
dtype: float64

In [33]:
# Creating Series with Specified Index Labels (row labels)

s1 = pd.Series(array, index = np.arange(10,20))
s1               # Row labels: 10,11,12,13,.....19

10     8
11     5
12     5
13     7
14     0
15     8
16     1
17     6
18     7
19    14
dtype: int32

In [34]:
s1 = pd.Series(array, index = ['A','B','C','D','E'])        

# ValueError: no. of rows not matched with array items (10 rows but 5 passes)

ValueError: Length of values (10) does not match length of index (5)

In [35]:
s1 = pd.Series(array, index = ['A','B','C','D','E','F','G','H','I','J']) 
s1

A     8
B     5
C     5
D     7
E     0
F     8
G     1
H     6
I     7
J    14
dtype: int32

In [36]:
# Creating Series from Scalar Value
value = 10
s1 = pd.Series(value,index = list('ABCDEF'))
s1                                            # all rows contains same value

A    10
B    10
C    10
D    10
E    10
F    10
dtype: int64

In [37]:
# Numpy Function: np.zeros()

s2 = pd.Series(np.zeros(10))
s2                              # Default Datatype: float

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
6    0.0
7    0.0
8    0.0
9    0.0
dtype: float64

In [38]:
# Numpy Function: np.ones()

s2 = pd.Series(np.ones(15))
s2  

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
dtype: float64

In [39]:
# Numpy Function: np.full()

s2 = pd.Series(np.full(13,15))     # value is 15 for 13 no. of rows
s2 

0     15
1     15
2     15
3     15
4     15
5     15
6     15
7     15
8     15
9     15
10    15
11    15
12    15
dtype: int32

In [41]:
s2 = pd.Series(np.full(8,'A'))
s2                                     # Datatype is: object (because value is string)

0    A
1    A
2    A
3    A
4    A
5    A
6    A
7    A
dtype: object

In [49]:
# Numpy Function: np.linspace()

s1 = pd.Series(np.linspace(1,25,5))
print("First Series is:\n", s1)
print('*'* 45)
s2 = pd.Series(np.linspace(10,100,10))
print('Second Series is:\n', s2)

First Series is:
 0     1.0
1     7.0
2    13.0
3    19.0
4    25.0
dtype: float64
*********************************************
Second Series is:
 0     10.0
1     20.0
2     30.0
3     40.0
4     50.0
5     60.0
6     70.0
7     80.0
8     90.0
9    100.0
dtype: float64


In [52]:
# Creating Series with Range function
s1 = pd.Series(range(10))
s1

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [67]:
# Creating Series using for loop and List Comprehension

# Rows: A,B,C,D,E
# Values: range(10,25) with size of 3

s1 = pd.Series(range(10,25,3), index = [i for i in 'ABCDE'])
s1


A    10
B    13
C    16
D    19
E    22
dtype: int64

In [71]:
# Creating Series using Mathematical Operations
# Multiples of 10 for integers from 12 to 19

array = np.arange(12,19)
print(array)
result = pd.Series(array*10)              # each item of the array multiplies by 10
result

[12 13 14 15 16 17 18]


0    120
1    130
2    140
3    150
4    160
5    170
6    180
dtype: int32

In [77]:
array = np.arange(12,19)
print(array.tolist())
result = pd.Series(lambda x: x*5)          
result([1,2,3,4])                          # Series- object is not callable

[12, 13, 14, 15, 16, 17, 18]


TypeError: 'Series' object is not callable

In [95]:
# Creating Series using User Defined Functions

# Fibonacci Series 

def fibo(x):
    if x == 0:
        return x
    elif x == 1:
        return x
    else:
        return fibo(x-1)+fibo(x-2)
n = 10 
print(f'Fibonaci Series of {n} terms:')
for i in range(n):
    x = fibo(i)
    print(x, end = ' ')
s1 = pd.Series([fibo(i) for i in range(n)], index = list(range(1,11)))
s1

Fibonaci Series of 10 terms:
0 1 1 2 3 5 8 13 21 34 

1      0
2      1
3      1
4      2
5      3
6      5
7      8
8     13
9     21
10    34
dtype: int64

#### 2. Data Frame

In [ ]:
Data Frame: 
    DataFrame is Two Dimensional Data Structure.
    Data is aligned in Tabular Format of rows and columns

syntax:
    df = pd.DataFrame(data, index = None, columns = None, dtype = None)

data: rows and columns --> can be list, tuple, dict (keys--> col labels, values -->records)
index: row labels (optional), default start from 0
columns: col labels (optional), default start from 0
dtype: None (optional) 

Data Frame has 3 Components:
    1. Rows    >> also called as index
    2. Columns
    3. Data    >> value present in the cell

Datatype of Data Frame:
    pandas.core.frame.DataFrame


In [99]:
array = np.random.randint(10,50, size = (4,6))
print(array, 'Dimention:',array.ndim)


[[32 21 27 44 11 12]
 [22 10 22 29 21 16]
 [34 39 27 10 43 20]
 [16 48 12 18 33 35]] Dimention: 2


In [100]:
df1 = pd.DataFrame(array)
df1

0   1   2   3   4   5
0  32  21  27  44  11  12
1  22  10  22  29  21  16
2  34  39  27  10  43  20
3  16  48  12  18  33  35

In [27]:
# columns names can be changed

df1 = pd.DataFrame(array, columns = ['A','B','C','D','E','F'])
df1

A   B   C   D   E   F
0  33  24  17  11  42  32
1  13  34  45  25  25  10
2  10  23  30  11  38  14
3  33  46  46  14  27  30

In [30]:
# calling of specific column
# Results in series if No. of Columns = 1

df2 = df1['B']
print(df2)
print(type(df2))

0    24
1    34
2    23
3    46
Name: B, dtype: int32
<class 'pandas.core.series.Series'>


In [32]:
# calling of specific column
# Results in DataFrame if No. of Columns > 1

df2 = df1[['A','B']]                 # multiple columns shall be passed in List
print(df2)
print(type(df2))

    A   B
0  33  24
1  13  34
2  10  23
3  33  46
<class 'pandas.core.frame.DataFrame'>


In [125]:
# Empty Data Frame

df = pd.DataFrame()
print(df)
df

Empty DataFrame
Columns: []
Index: []


Empty DataFrame
Columns: []
Index: []

### Creating Data Frames

#### 1. Using Lists:

In [103]:
list1 = [10,22,23,3,4,5,6,67,23]
df = pd.DataFrame(list1)
df                                    

0
0  10
1  22
2  23
3   3
4   4
5   5
6   6
7  67
8  23

In [104]:
type(df)                # Datatype of Data Frame

pandas.core.frame.DataFrame

In [101]:
list1 = [[1,2,3,4], [10,11,12,13]]           # list in list
df = pd.DataFrame(list1)
df                                          

0   1   2   3
0   1   2   3   4
1  10  11  12  13

In [106]:
df = pd.DataFrame(list('ABCDEFGH'))
df

0
0  A
1  B
2  C
3  D
4  E
5  F
6  G
7  H

In [116]:
# Condition: len(list1) = len(list2)

list1 = [10,20,30,40,50]                 # as row values
list2 = ['A','B','C','D','E']            # as Row Labels
df = pd.DataFrame(list1,list2)
df

0
A  10
B  20
C  30
D  40
E  50

#### 2. Using Tuple:

In [107]:
tuple1 = (5,6,7,4,5,6,4,2)
df = pd.DataFrame(tuple1)                 
df

0
0  5
1  6
2  7
3  4
4  5
5  6
6  4
7  2

In [108]:
tuple1 = ((5,6,7,4),(5,6,4,2))              # tuple in tuple
df = pd.DataFrame(tuple1)                  
df

0  1  2  3
0  5  6  7  4
1  5  6  4  2

In [117]:
tuple1 = (5,6,7,4,5,6,)
tuple2 = (list('python'))
df = pd.DataFrame(tuple1, tuple2)                  
df

0
p  5
y  6
t  7
h  4
o  5
n  6

#### 3. Using Dictionary:

In [ ]:
dict = {key:value}
Keys   -> Column Labels
Values -> value of the rows

In [110]:
d1 = {'A': [1,2,3,4,5,6,7,8,9]}
df = pd.DataFrame(d1)
df                                

A
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
8  9

In [115]:
d1 = {'A': [1,2,3,4,5,6,7,8,9],
      'B': [11,12,13,14,15,16,17,18,19]
     }
df = pd.DataFrame(d1)
df                                       

A   B
0  1  11
1  2  12
2  3  13
3  4  14
4  5  15
5  6  16
6  7  17
7  8  18
8  9  19

In [118]:
# Values with different datatype constructors

dict1 = {'A': [10,20,30,40],
         'B': (2,3,5,7),
         'C': np.array(['p',4,6,8]),
         'D': np.arange(101,105)
        }
df = pd.DataFrame(dict1)
df  

A  B  C    D
0  10  2  p  101
1  20  3  4  102
2  30  5  6  103
3  40  7  8  104

In [119]:
dict1 = {'A': [10,20,30,40],
         'B': (2,3,5,7),
         'C': np.array(['p',4,6,8]),
         'D': np.arange(101,105),
         'E': pd.Series(['p','y','t','h'])
        }
df = pd.DataFrame(dict1)
df      

A  B  C    D  E
0  10  2  p  101  p
1  20  3  4  102  y
2  30  5  6  103  t
3  40  7  8  104  h

#### 4. Using Numpy Arrays:

In [120]:
array = np.random.randint(1,100,size = (10,5))       # rows = 10, columns = 5
array

array([[64, 32, 85, 93, 62],
       [33, 32, 15, 12, 23],
       [48,  7, 92, 80, 61],
       [67, 96, 65, 98, 34],
       [28, 32, 35, 24,  8],
       [ 3, 69, 56, 71, 37],
       [43, 86, 74, 77, 87],
       [44, 47, 58, 56, 31],
       [34, 41, 20, 95, 79],
       [62, 86, 69, 92, 16]])

In [121]:
df1 = pd.DataFrame(array)
print(df1)
df1

    0   1   2   3   4
0  64  32  85  93  62
1  33  32  15  12  23
2  48   7  92  80  61
3  67  96  65  98  34
4  28  32  35  24   8
5   3  69  56  71  37
6  43  86  74  77  87
7  44  47  58  56  31
8  34  41  20  95  79
9  62  86  69  92  16


0   1   2   3   4
0  64  32  85  93  62
1  33  32  15  12  23
2  48   7  92  80  61
3  67  96  65  98  34
4  28  32  35  24   8
5   3  69  56  71  37
6  43  86  74  77  87
7  44  47  58  56  31
8  34  41  20  95  79
9  62  86  69  92  16

In [133]:
# Numpy Function: np.zeros()

zero_array = np.zeros((10,5),dtype = int)
zero_array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [134]:
data_frame1 = pd.DataFrame(zero_array)
print(data_frame1)
data_frame1                    # Data Frame has all 0's

   0  1  2  3  4
0  0  0  0  0  0
1  0  0  0  0  0
2  0  0  0  0  0
3  0  0  0  0  0
4  0  0  0  0  0
5  0  0  0  0  0
6  0  0  0  0  0
7  0  0  0  0  0
8  0  0  0  0  0
9  0  0  0  0  0


0  1  2  3  4
0  0  0  0  0  0
1  0  0  0  0  0
2  0  0  0  0  0
3  0  0  0  0  0
4  0  0  0  0  0
5  0  0  0  0  0
6  0  0  0  0  0
7  0  0  0  0  0
8  0  0  0  0  0
9  0  0  0  0  0

In [48]:
# Numpy Function: np.ones()

one_array = np.ones((5,6), dtype = int)
df_one = pd.DataFrame(one_array)
print(df_one)
df_one                                   # Data Frame has all 1's

   0  1  2  3  4  5
0  1  1  1  1  1  1
1  1  1  1  1  1  1
2  1  1  1  1  1  1
3  1  1  1  1  1  1
4  1  1  1  1  1  1


0  1  2  3  4  5
0  1  1  1  1  1  1
1  1  1  1  1  1  1
2  1  1  1  1  1  1
3  1  1  1  1  1  1
4  1  1  1  1  1  1

In [131]:
# Scalar Value using Numpy Function: np.full()

df = pd.DataFrame(np.full((3,5),23))
df                                 # Data Frame has all values same


0   1   2   3   4
0  23  23  23  23  23
1  23  23  23  23  23
2  23  23  23  23  23

In [136]:
df = pd.DataFrame(np.full((3,5),23.5))            # Data Type is Float
df                                 # Data Frame has all values same


0     1     2     3     4
0  23.5  23.5  23.5  23.5  23.5
1  23.5  23.5  23.5  23.5  23.5
2  23.5  23.5  23.5  23.5  23.5

In [137]:
df = pd.DataFrame(np.full((3,5),23.5, dtype = int))      # Datatype is int
df                                 # Data Frame has all values int same


0   1   2   3   4
0  23  23  23  23  23
1  23  23  23  23  23
2  23  23  23  23  23

In [135]:
df = pd.DataFrame(np.full((3,5),'A'))
df                                 # Data Frame has all values same


0  1  2  3  4
0  A  A  A  A  A
1  A  A  A  A  A
2  A  A  A  A  A

#### 5. Using Custom Index Labels

In [152]:
col_vals = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
row_labels = ['A','B','C']
df = pd.DataFrame(col_vals,row_labels)
df 

# Here, row labels will A,B,C

0   1   2   3   4
A   1   2   3   4   5
B   6   7   8   9  10
C  11  12  13  14  15

### Examples on Data Frames

#### Creating Fibonacci Series in DF

In [18]:
# Data Frame of Fibo Series of 20 No.s in (2,10) shape
def fibo(x):
    if x == 0:
        return x
    elif x == 1:
        return x
    else:
        return fibo(x-1)+fibo(x-2)
n = 20
fibo_list = [fibo(i) for i in range(n)]              # Fibo list
fibo_array = np.array(fibo_list)                     # Fibo list converted into Np Array
fibo_df = pd.DataFrame(fibo_array.reshape(2,10))     # Data Frame of size (2,10)
fibo_df

0   1    2    3    4    5    6     7     8     9
0   0   1    1    2    3    5    8    13    21    34
1  55  89  144  233  377  610  987  1597  2584  4181

### Comparision of Series and Data Frame in 1-Dimension

In [ ]:
Series:
    1-D  >> one column with its values
Data Frame:
    2-D  >> row and column
    
Single Column DF can be converted into a Series


In [157]:
x = np.arange(100,110)
df = pd.DataFrame(x)                      # Data Frame with Single Column
print(df)
print(type(df))                           # frame.DataFrame

     0
0  100
1  101
2  102
3  103
4  104
5  105
6  106
7  107
8  108
9  109
<class 'pandas.core.frame.DataFrame'>


In [159]:
x = np.arange(100,110)
df = pd.Series(x)                      # Series with Single Column
print(df)
print(type(df))                        # series.Series'

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int32
<class 'pandas.core.series.Series'>


In [163]:
var = np.arange(10,25,2)
var_series = pd.Series(var)
var_df = pd.DataFrame(var)
print('Variable Series is:\n', var_series)
print('Variable Data Frame is:\n', var_df)


Variable Series is:
 0    10
1    12
2    14
3    16
4    18
5    20
6    22
7    24
dtype: int32
Variable Data Frame is:
     0
0  10
1  12
2  14
3  16
4  18
5  20
6  22
7  24


#### Modifications of Columns and its values:

In [ ]:
If column already exists: 
    Original records will be replace with New Values
If column not exist:
    New column will be added at the end

In [168]:
# To replace the original records
dict1 = {'A': [10,20,30,40],
         'B': (2,3,5,7),
         'C': np.array(['p',4,6,8]),
         'D': np.arange(101,105),
         'E': pd.Series(['p','y','t','h'])
        }
df = pd.DataFrame(dict1)
print('Original DataFrame:')
print(df)
df['C'] = ('x','y','z','k')
print('Updated DataFrame:')
print(df)                        # C-column will be updated

Original DataFrame:
    A  B  C    D  E
0  10  2  p  101  p
1  20  3  4  102  y
2  30  5  6  103  t
3  40  7  8  104  h
Updated DataFrame:
    A  B  C    D  E
0  10  2  x  101  p
1  20  3  y  102  y
2  30  5  z  103  t
3  40  7  k  104  h


In [169]:
# To add one more column to the Data Frame

df['F'] = pd.Series([1,8,27,64])
df                                 # F' column will be added

A  B  C    D  E   F
0  10  2  x  101  p   1
1  20  3  y  102  y   8
2  30  5  z  103  t  27
3  40  7  k  104  h  64

## Reading Data from Files:           Input/Output

In [ ]:
1. CSV:
    To Read: 
        pd.read_csv(r'filepath\file_name.csv')
    To Convert DF:
        df.to_csv(r'filepath\file_name.csv')
        
2. Excel:
    To Read:
        pd.read_excel(r'filepath\file_name.xlsx')
    To Convert DF:
        df.to_excel(r'filepath\file_name.xlsx')
        
3. Pickle:
    To Read:
        pd.read_pkl(r'filepath\file_name.pkl')
    To Convert DF:
        df.to_pickle(r'filepath\file_name.pkl')
        
4. JSON:
    To Read:
        pd.read_json(r'filepath\file_name.json')
    To Convert DF:
        df.to_html(r'filepath\file_name.json')
        
5. HTML:
    To Read:
        pd.read_html(r'filepath\file_name.html')
    To Convert DF:
        df.to_html(r'filepath\file_name.html')
        
6. SQL:
    To Read:
        pd.read_sql_table(r'filepath\file_name.sql', con)       # read SQL Table
        pd.read_sql_query(r'filepath\file_name.sql', con)       # read SQL Query Database
        pd.read_sql(r'filepath\file_name.sql', con)             # read SQL Table or Query DB
    To Convert DF:
        df.to_sql(r'filepath\file_name.sql')
        
    Note: con >> Database Configuration should specify to read SQL file
7. STATA:
    To Read:
        pd.read_stata(r'filepath\file_name.dta')
    To Convert DF:
        df.to_stata(r'filepath\file_name.dta')


#### From CSV File:

In [83]:
df = pd.read_csv(r'C:\Users\Kiran\Practice Python\Important Files\Data Sets\ipl-matches.csv')
df

ID        City       Date   Season  MatchNumber  \
0    1312200   Ahmedabad  5/29/2022     2022        Final   
1    1312199   Ahmedabad  5/27/2022     2022  Qualifier 2   
2    1312198     Kolkata  5/25/2022     2022   Eliminator   
3    1312197     Kolkata  5/24/2022     2022  Qualifier 1   
4    1304116      Mumbai  5/22/2022     2022           70   
..       ...         ...        ...      ...          ...   
945   335986     Kolkata  4/20/2008  2007/08            4   
946   335985      Mumbai  4/20/2008  2007/08            5   
947   335984       Delhi  4/19/2008  2007/08            3   
948   335983  Chandigarh  4/19/2008  2007/08            2   
949   335982   Bangalore  4/18/2008  2007/08            1   

                           Team1                        Team2  \
0               Rajasthan Royals               Gujarat Titans   
1    Royal Challengers Bangalore             Rajasthan Royals   
2    Royal Challengers Bangalore         Lucknow Super Giants   
3               Rajasthan Royals               Gujarat Titans   
4            Sunrisers Hyderabad                 Punjab Kings   
..                           ...                          ...   
945        Kolkata Knight Riders              Deccan Chargers   
946               Mumbai Indians  Royal Challengers Bangalore   
947             Delhi Daredevils             Rajasthan Royals   
948              Kings XI Punjab          Chennai Super Kings   
949  Royal Challengers Bangalore        Kolkata Knight Riders   

                                          Venue                   TossWinner  \
0              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals   
1              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals   
2                         Eden Gardens, Kolkata         Lucknow Super Giants   
3                         Eden Gardens, Kolkata               Gujarat Titans   
4                      Wankhede Stadium, Mumbai          Sunrisers Hyderabad   
..                                          ...                          ...   
945                                Eden Gardens              Deccan Chargers   
946                            Wankhede Stadium               Mumbai Indians   
947                            Feroz Shah Kotla             Rajasthan Royals   
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings   
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore   

    TossDecision SuperOver                  WinningTeam    WonBy  Margin  \
0            bat         N               Gujarat Titans  Wickets     7.0   
1          field         N             Rajasthan Royals  Wickets     7.0   
2          field         N  Royal Challengers Bangalore     Runs    14.0   
3          field         N               Gujarat Titans  Wickets     7.0   
4            bat         N                 Punjab Kings  Wickets     5.0   
..           ...       ...                          ...      ...     ...   
945          bat         N        Kolkata Knight Riders  Wickets     5.0   
946          bat         N  Royal Challengers Bangalore  Wickets     5.0   
947          bat         N             Delhi Daredevils  Wickets     9.0   
948          bat         N          Chennai Super Kings     Runs    33.0   
949        field         N        Kolkata Knight Riders     Runs   140.0   

    method Player_of_Match                                       Team1Players  \
0      NaN       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
1      NaN      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
2      NaN      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
3      NaN       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
4      NaN   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...   
..     ...             ...                                                ...   
945    NaN       DJ Hussey  ['WP Saha', 'BB McCullum', 

In [85]:
df2 = pd.read_csv('loan_data.csv')
df2

credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1         credit_card    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1         credit_card    0.1426       102.92   
...             ...                 ...       ...          ...   
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0    home_improvement    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 14 columns]

In [12]:
array = np.random.randint(1,100,size = (10,5))      
df = pd.DataFrame(array)
df.to_csv(r'C:\Users\Kiran\Practice Python\Important Files\Data Sets\Working Samples\Random.csv')

# DataFrame converted into a CSV file, created in the above directory

#### From Excel File:

In [175]:
import pandas as pd
df1 = pd.read_csv(r'C:\Users\Kiran\Practice Python\Important Files\Data Sets\Emp_data.csv')
df1

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

In [13]:
array = np.random.randint(1,100,size = (10,5))      
df = pd.DataFrame(array)
df.to_excel(r'C:\Users\Kiran\Practice Python\Important Files\Data Sets\Working Samples\Random.xlsx')

# DataFrame converted into a Excel file, created in the above directory

#### 3. Pickle File:

In [16]:
df_pkl = pd.read_pickle(r'C:\Users\Kiran\Practice Python\Important Files\Data Sets\dummy.pkl')
df_pkl

ID        City       Date   Season  MatchNumber  \
0    1312200   Ahmedabad  5/29/2022     2022        Final   
1    1312199   Ahmedabad  5/27/2022     2022  Qualifier 2   
2    1312198     Kolkata  5/25/2022     2022   Eliminator   
3    1312197     Kolkata  5/24/2022     2022  Qualifier 1   
4    1304116      Mumbai  5/22/2022     2022           70   
..       ...         ...        ...      ...          ...   
945   335986     Kolkata  4/20/2008  2007/08            4   
946   335985      Mumbai  4/20/2008  2007/08            5   
947   335984       Delhi  4/19/2008  2007/08            3   
948   335983  Chandigarh  4/19/2008  2007/08            2   
949   335982   Bangalore  4/18/2008  2007/08            1   

                           Team1                        Team2  \
0               Rajasthan Royals               Gujarat Titans   
1    Royal Challengers Bangalore             Rajasthan Royals   
2    Royal Challengers Bangalore         Lucknow Super Giants   
3               Rajasthan Royals               Gujarat Titans   
4            Sunrisers Hyderabad                 Punjab Kings   
..                           ...                          ...   
945        Kolkata Knight Riders              Deccan Chargers   
946               Mumbai Indians  Royal Challengers Bangalore   
947             Delhi Daredevils             Rajasthan Royals   
948              Kings XI Punjab          Chennai Super Kings   
949  Royal Challengers Bangalore        Kolkata Knight Riders   

                                          Venue                   TossWinner  \
0              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals   
1              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals   
2                         Eden Gardens, Kolkata         Lucknow Super Giants   
3                         Eden Gardens, Kolkata               Gujarat Titans   
4                      Wankhede Stadium, Mumbai          Sunrisers Hyderabad   
..                                          ...                          ...   
945                                Eden Gardens              Deccan Chargers   
946                            Wankhede Stadium               Mumbai Indians   
947                            Feroz Shah Kotla             Rajasthan Royals   
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings   
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore   

    TossDecision SuperOver                  WinningTeam    WonBy  Margin  \
0            bat         N               Gujarat Titans  Wickets     7.0   
1          field         N             Rajasthan Royals  Wickets     7.0   
2          field         N  Royal Challengers Bangalore     Runs    14.0   
3          field         N               Gujarat Titans  Wickets     7.0   
4            bat         N                 Punjab Kings  Wickets     5.0   
..           ...       ...                          ...      ...     ...   
945          bat         N        Kolkata Knight Riders  Wickets     5.0   
946          bat         N  Royal Challengers Bangalore  Wickets     5.0   
947          bat         N             Delhi Daredevils  Wickets     9.0   
948          bat         N          Chennai Super Kings     Runs    33.0   
949        field         N        Kolkata Knight Riders     Runs   140.0   

    method Player_of_Match                                       Team1Players  \
0      NaN       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
1      NaN      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
2      NaN      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
3      NaN       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
4      NaN   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...   
..     ...             ...                                                ...   
945    NaN       DJ Hussey  ['WP Saha', 'BB McCullum', 

In [17]:
array = np.random.randint(1,100,size = (10,5))      
df = pd.DataFrame(array)
df.to_pickle(r'C:\Users\Kiran\Practice Python\Important Files\Data Sets\Working Samples\Random.pkl')

# DataFrame converted into a PKL file, created in the above directory

#### From JSON File

In [23]:
array = np.random.randint(1,100,size = (10,5))      
df = pd.DataFrame(array)
df.to_json(r'C:\Users\Kiran\Practice Python\Important Files\Data Sets\JSONsample.json')

In [24]:
df_json = pd.read_json(r'C:\Users\Kiran\Practice Python\Important Files\Data Sets\JSONsample.json')
df_json

0   1   2   3   4
0  86  98  47  94  13
1  46  28  64  69  24
2  96  72  43   9  96
3  88  38  69  32  93
4  48  30  32  35  58
5  26  62  76  23   9
6  81  27  90  42  22
7  71  64  10  49  98
8  74   9  10  73  70
9  69  96  22  47  52

#### From STATA File

In [27]:
df = pd.read_stata(r'C:\Users\Kiran\Practice Python\Important Files\Data Sets\airline.dta')
df

year          y      w       r      l      k
0   1948   1.214000  0.243  0.1454  1.415  0.612
1   1949   1.354000  0.260  0.2181  1.384  0.559
2   1950   1.569000  0.278  0.3157  1.388  0.573
3   1951   1.948000  0.297  0.3940  1.550  0.564
4   1952   2.265000  0.310  0.3559  1.802  0.574
5   1953   2.731000  0.322  0.3593  1.926  0.711
6   1954   3.025000  0.335  0.4025  1.964  0.776
7   1955   3.562000  0.350  0.3961  2.116  0.827
8   1956   3.979000  0.361  0.3822  2.435  0.800
9   1957   4.420000  0.379  0.3045  2.707  0.921
10  1958   4.563000  0.391  0.3284  2.706  1.067
11  1959   5.385000  0.426  0.3856  2.846  1.083
12  1960   5.554000  0.441  0.3193  3.089  1.481
13  1961   5.465000  0.460  0.3079  3.122  1.736
14  1962   5.825000  0.485  0.3783  3.184  1.926
15  1963   6.876000  0.506  0.4180  3.263  2.041
16  1964   7.823000  0.538  0.5163  3.412  1.997
17  1965   9.120000  0.564  0.5879  3.623  2.257
18  1966  10.512000  0.586  0.5369  4.074  2.742
19  1967  13.020000  0.622  0.4443  4.710  3.564
20  1968  15.261000  0.666  0.3052  5.217  4.767
21  1969  16.313000  0.731  0.2332  5.569  6.511
22  1970  16.002001  0.831  0.1883  5.495  7.627
23  1971  15.876000  0.906  0.2023  5.334  8.673
24  1972  16.662001  1.000  0.2506  5.345  8.331
25  1973  17.014000  1.056  0.2668  5.662  8.557
26  1974  19.305000  1.131  0.2664  5.729  9.508
27  1975  18.721001  1.247  0.2301  5.722  9.062
28  1976  19.250000  1.375  0.3452  5.762  8.262
29  1977  20.646999  1.544  0.4508  5.877  7.474
30  1978  22.726000  1.703  0.5877  6.108  7.104
31  1979  23.618999  1.779  0.5346  6.852  6.874

In [28]:
array = np.random.randint(1,100,size = (10,5))      
df = pd.DataFrame(array)
df.to_json(r'C:\Users\Kiran\Practice Python\Important Files\Data Sets\Working Samples\Random.dta')

# DataFrame converted into a DTA file, created in the above directory